version: 1.0.{build}

os: Visual Studio 2015

clone_folder: C:\projects\raytracing

branches:
  only:
    - master

configuration:
  - Debug
  - Release

platform:
  - Win32
  - x64
  # - ARM

before_build:
  - git submodule update --init --recursive

build_script:
  - cd C:\projects\raytracing
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015" -A %PLATFORM% .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE -DRTX_WITH_POST_BUILD_UNITTEST=OFF
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=%CONFIGURATION% /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% raytracing.sln

after_build:
  - 7z a -r build.zip C:\projects\raytracing\build\bin\%CONFIGURATION%\*

test_script:
  - C:\projects\raytracing\build\bin\%CONFIGURATION%\rtx_test.exe

artifacts:
  - path: build.zip
    name: Raytracing-%CONFIGURATION%-%PLATFORM%