version: 1.0.{build}
os: Visual Studio 2015
test: off
clone_folder: C:\projects\raytracing
branches:
  only:
    - master
install:
  - git submodule update --init --recursive
build_script:
  - echo Running cmake...
  - cd c:\projects\raytracing
  - cmake -G "Visual Studio 14 2015 Win64" .
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=Release /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% raytracing.sln
on_finish:
  - tree