version: "build-{build}-{branch}"

image:
  - Visual Studio 2017
  - Ubuntu

platform:
  - x64

configuration:
  - Release

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

install:
  - git submodule update --init --recursive

  - ps: if (-not(Test-Path("build"))) { mkdir build }
  - sh: mkdir -p build
  - cd build

  - ps: "./install-opengl.ps1"

  - sh: sudo add-apt-repository ppa:ubuntu-x-swat/updates 
  - sh: sudo apt-get upgrade -y
  - sh: sudo apt-get dist-upgrade -y
  - sh: sudo apt-get install xorg-dev libx11-xcb-dev libxcb-render0-dev libxcb-render-util0-dev libgl-dev -y

for:
  - matrix:
      only:
        - image: Ubuntu
    before_build:
      - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=%CONFIGURATION%
    build_script:
      - cmake --build . --config %CONFIGURATION%

  - matrix:
      only:
        - image: Visual Studio 2017
    before_build:
      - cmake .. -G "Visual Studio 15 2017" -A x64
    build_script:
      - cmake --build . --config %CONFIGURATION%
      - msbuild %APPVEYOR_PROJECT_NAME%.sln

on_finish:
  - ps: "./install-opengl.ps1 uninstall"