version: "build-{build}-{branch}"

image:
  - Visual Studio 2017
  - Ubuntu

platform:
  - x64

configuration:
  - Release

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

install:
  - git submodule update --init --recursive

  - ps: if (-not(Test-Path("build"))) { mkdir build }
  - sh: mkdir -p build
  - cd build

  - sh: sudo apt install libxrandr-dev

for:
  - matrix:
      only:
        - image: Ubuntu
    before_build:
      - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=%CONFIGURATION%
    build_script:
      - cmake --build . --config %CONFIGURATION%

  - matrix:
      only:
        - image: Visual Studio 2017
    before_build:
      - cmake .. -G "Visual Studio 15 2017" -A x64
    build_script:
      - cmake --build . --config %CONFIGURATION%
      - msbuild %APPVEYOR_PROJECT_NAME%.sln
